services:
  - type: web
    name: lazyt-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn lazyT_api.wsgi
